version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo "Exporting environment..."
      - export LAMBDA_URI=$LAMBDA_URI
      - chmod +x generate-api.sh
      - ./generate-api.sh
  build:
    commands:
      - echo Running tests...
      - npm test

artifacts:
  files:
    - '**/*'
