version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Building secure api.yaml...
      - node build-openapi.js
      - echo Generating API documentation...
      - npx redoc-cli bundle api.yaml -o docs/api-doc.html

  build:
    commands:
      - echo Running tests...
      - npm test
      - npm run coverage

artifacts:
  files:
    - lambda/**      # chỉ đưa thư mục lambda vào artifact
  discard-paths: no
